defaultMailer:
  host: <smtp_host>
  port: <smtp_port_number>
  secure: false
  auth:
    user: <email>
    pass: <pass>
defaults:
    from: <email>
sendGrid:
    apiKey: <api_key>
templateDir: ./src/email-templates
mailerType: 0 #0: default mailer, 1: sendgrid mailer, 2: extend mailer

